name: ensure_initialized
version: 0.1.0
description: Allows to await for an object's initialization before using it.
homepage: https://github.com/nivisi/ensure_initialized
repository: https://github.com/nivisi/ensure_initialized

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  meta: ^1.3.0

dev_dependencies:
  test: ^1.20.1