name: ⚙️ CI

on:
  push:
    branches: [ develop ]
    paths:
      - lib/**
      - .github/workflows/ci.yml
      - main.dart

  pull_request:
    paths:
      - lib/**
      - .github/workflows/ci.yml
      - main.dart

  workflow_dispatch:

jobs:
  CheckCodebase:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1.3

      - name: Get packages
        run: dart pub get

      - name: Check formatting
        run: dart format --set-exit-if-changed .

      - name: Analyze
        run: dart analyze .
